-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : dim. 13 juil. 2025 à 09:34
-- Version du serveur : 8.0.42-0ubuntu0.24.04.2
-- Version de PHP : 8.3.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `blog-cfpc`
--

-- --------------------------------------------------------

--
-- Structure de la table `articles`
--

CREATE TABLE `articles` (
  `id` int NOT NULL,
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `category_id` int DEFAULT NULL,
  `introduction` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `articles`
--

INSERT INTO `articles` (`id`, `image`, `title`, `slug`, `category_id`, `introduction`, `content`, `created_at`, `updated_at`) VALUES
(4, NULL, 'Formation Développeur Web Full-Stack', 'formation-developpeur-web-full-stack', NULL, 'Cette formation intensive de 12 semaines est conçue pour transformer les débutants en développeurs web full-stack compétents.', 'Le programme couvre les fondamentaux du développement web, y compris HTML, CSS, JavaScript, Node.js, React et MongoDB. Les participants apprendront à créer des applications web complètes, de la conception à la mise en production. Des projets pratiques permettront de consolider les compétences acquise', '2025-05-06 20:54:04', NULL),
(6, NULL, 'Bootcamp Développement Mobile avec Flutter', 'bootcamp-developpement-mobile-avec-flutter', NULL, 'Ce bootcamp de 8 semaines offre une immersion complète dans le développement d&#039;applications mobiles multiplateformes avec Flutter.', 'Les participants apprendront à concevoir des interfaces utilisateur réactives, à gérer l&#039;état des applications et à intégrer des services backend. Le bootcamp inclut des projets pratiques pour développer des applications mobiles fonctionnelles', '2025-05-06 20:56:10', NULL),
(7, NULL, 'Atelier Pratique : Développement d&#039;Applications Web avec React.js', 'atelier-pratique-developpement-d039applications-web-avec-reactjs', NULL, 'Rejoignez notre atelier intensif de 3 jours dédié au développement d&#039;applications web modernes en utilisant React.js. Conçu pour les développeurs souhaitant approfondir leurs compétences en front-end, cet atelier vous permettra de maîtriser les concepts fondamentaux de React et de construire des interfaces utilisateur dynamiques et réactives.', 'Au cours de cet atelier, les participants exploreront les principes clés de React.js, y compris la création de composants, la gestion de l&#039;état avec hooks, le routage avec React Router et l&#039;intégration d&#039;API RESTful. Chaque session combinera des explications théoriques avec des exercices pratiques pour renforcer l&#039;apprentissage.\r\n\r\nLes participants auront l&#039;occasion de travailler sur un projet de bout en bout, développant une application web complète qui intègre les fonctionnalités apprises. Ce projet servira de portfolio pour démontrer les compétences acquises.\r\n\r\nL&#039;atelier sera animé par des experts en développement web ayant une expérience significative dans la création d&#039;applications React en production. Ils partageront des astuces, des bonnes pratiques et des retours d&#039;expérience pour aider les participants à éviter les pièges courants et à adopter des approches efficaces.\r\n\r\nInformations pratiques :\r\n\r\nDates : Du 15 au 17 juin 2025\r\n\r\nLieu : Centre de Conférences TechHub, Bamenda, Cameroun\r\n\r\nHoraires : 9h00 - 17h00 chaque jour\r\n\r\nPrérequis : Connaissances de base en JavaScript et HTML/CSS\r\n\r\nMatériel requis : Ordinateur portable avec Node.js et un éditeur de code installés\r\n\r\nInscription :\r\nPour vous inscrire, veuillez remplir le formulaire en ligne disponible sur notre site web. Les places sont limitées à 25 participants pour garantir une interaction optimale avec les formateurs. Les frais d&#039;inscription s&#039;élèvent à 150 000 FCFA, couvrant les supports de cours, les pauses-café et les déjeuners.\r\n\r\nNe manquez pas cette opportunité de renforcer vos compétences en développement web et de rejoindre une communauté de professionnels passionnés par la technologie.', '2025-05-06 20:57:43', NULL),
(8, NULL, 'L&#039;Intelligence Artificielle Générative : Révolution Créative ou Défi Éthique ?', 'l039intelligence-artificielle-generative-revolution-creative-ou-defi-ethique', NULL, 'Les modèles d&#039;IA générative comme GPT-4, DALL-E et Stable Diffusion ont redéfini les frontières entre créativité humaine et machine.', 'ontenu :\r\n\r\nFondations techniques : Architecture Transformer, mécanismes d&#039;attention et apprentissage auto-supervisé sur des corpus multimodaux (texte, image, code).\r\nApplications : Génération de code (GitHub Copilot), création artistique algorithmique, synthèse de données pour la R&amp;D.\r\nEnjeux éthiques : Biais des données d&#039;entraînement, plagiat algorithmique, impact sur les métiers créatifs.\r\nPerspectives : Modèles multimodaux capables de raisonnement causal (ex : AlphaFold 3 pour la biologie structurale).', '2025-05-06 21:01:23', NULL),
(9, NULL, 'Conférence Blockchain et Cryptomonnaies 2025', 'conference-blockchain-cryptomonnaies-2025', NULL, 'Découvrez les dernières avancées de la technologie blockchain et de l’écosystème des cryptomonnaies.', 'Cette conférence de deux jours rassemblera des experts internationaux pour discuter de la scalabilité, de la décentralisation, et des mécanismes de consensus. Au programme : ateliers pratiques sur le développement de smart contracts, tables rondes sur la réglementation et panels dédiés aux nouvelles applications DeFi et NFT.', '2025-05-06 21:10:00', NULL),
(10, NULL, 'Atelier Kubernetes Avancé', 'atelier-kubernetes-avance', NULL, 'Approfondissez vos compétences en orchestration de conteneurs avec Kubernetes dans un contexte de production.', 'Pendant cet atelier de trois jours, les participants apprendront à configurer des clusters haute disponibilité, à optimiser le scheduling, et à mettre en place Prometheus pour la supervision. Des cas pratiques incluent la migration d’une application monolithique vers un microservices orchestré.', '2025-05-06 21:11:00', NULL),
(11, NULL, 'Masterclass Sécurité API REST et GraphQL', 'masterclass-securite-api-rest-graphql', NULL, 'Maîtrisez les bonnes pratiques pour sécuriser vos APIs REST et GraphQL face aux menaces modernes.', 'Ce masterclass couvre l’authentification OAuth 2.0, l’autorisation fine-grain, la protection contre les attaques par injection, et le rate limiting. Sessions pratiques : audit de code, mise en place de WAF et tests d’intrusion.', '2025-05-06 21:12:00', NULL),
(12, NULL, 'Bootcamp DevOps : CI/CD et Infrastructure as Code', 'bootcamp-devops-ci-cd-infrastructure-as-code', NULL, 'Devenez un expert DevOps grâce à notre bootcamp intensif axé sur l’automatisation et l’IaC.', 'Sur 4 semaines, vous mettrez en place des pipelines CI/CD avec Jenkins et GitLab CI, déploierez des infrastructures AWS via Terraform, et gérerez la configuration avec Ansible. Le tout au travers d’un projet fil rouge prenant une application web de zéro à la production.', '2025-05-06 21:13:00', NULL),
(13, NULL, 'Webinaire UX/UI pour Développeurs Front-end', 'webinaire-ux-ui-pour-developpeurs-front-end', NULL, 'Initiez-vous aux principes de l’expérience utilisateur et du design d’interface orientés développeurs.', 'Ce webinaire d’une demi-journée présente les fondamentaux du design thinking, l’accessibilité (WCAG 2.1), et les workflows Figma pour collaborer efficacement avec les designers. Cas pratiques : prototypage rapide et tests utilisateurs.', '2025-05-06 21:14:00', NULL),
(14, NULL, 'Hackathon Intelligence Artificielle Responsable', 'hackathon-intelligence-artificielle-responsable', NULL, 'Participez à un hackathon de 48 h axé sur le développement d’IA éthiques et inclusives.', 'Les équipes auront accès à des datasets publics pour entraîner des modèles de machine learning tout en respectant les principes FAIR. Un jury d’experts évaluera les projets selon leur impact social, leur transparence et leur robustesse face aux biais.', '2025-05-06 21:15:00', NULL),
(15, NULL, 'Formation Python Avancé et Automatisation', 'formation-python-avance-automatisation', NULL, 'Passez du scripting basique à l’automatisation complexe avec Python et ses bibliothèques avancées.', 'Cette formation de 5 jours couvre l’asyncio, le traitement parallèle, la création de CLI avec Click, et l’utilisation de Robot Framework pour les tests automatiques. Des exercices vous guideront dans l’écriture de bots, la manipulation de fichiers XML/JSON et la connexion à des APIs externes.', '2025-05-06 21:16:00', NULL),
(16, NULL, 'Séminaire Big Data et Analyse Temps Réel', 'seminaire-big-data-analyse-temps-reel', NULL, 'Explorez les architectures Big Data et le traitement de flux en temps réel avec Kafka et Spark Streaming.', 'Ce séminaire de 3 jours alterne présentations théoriques et ateliers pratiques : ingestion de données depuis Kafka, écriture de jobs Spark Streaming, et visualisation de tableaux de bord via Grafana. Étude de cas : monitoring d’événements en direct.', '2025-05-06 21:17:00', NULL),
(17, NULL, 'Workshop Innovations IoT et Edge Computing', 'workshop-innovations-iot-edge-computing', NULL, 'Découvrez comment déployer des applications IoT performantes à l\'edge.', 'Au programme : plateformes MQTT, microservices conteneurisés sur Raspberry Pi, sécurité embarquée et intégration avec Azure IoT Hub. Chaque participant développera un prototype collectant et traitant des capteurs en temps réel.', '2025-05-06 21:18:00', NULL),
(18, NULL, 'Conférence DevSecOps : Intégrer la Sécurité au Développement', 'conference-devsecops-integrer-securite-developpement', NULL, 'Assistez à une journée dédiée à l’intégration native de la sécurité tout au long du cycle de vie logiciel.', 'Interventions de responsables sécurité et de développeurs pour partager des retours d’expérience sur l’automatisation des audits, la gestion des secrets et la remédiation continue via des pipelines sécurisés.', '2025-05-06 21:19:00', NULL),
(19, NULL, 'Atelier Microservices avec Spring Boot & Kubernetes', 'atelier-microservices-spring-boot-kubernetes', NULL, 'Apprenez à concevoir et déployer une architecture microservices résiliente en Java.', 'À travers un projet concret, vous développerez plusieurs microservices en Spring Boot, libériez une gateway API et orchestrerez le tout dans un cluster Kubernetes. Focus sur la tolérance aux pannes et l’observabilité.', '2025-05-06 21:20:00', NULL),
(20, NULL, 'Masterclass Design Patterns et Clean Code', 'masterclass-design-patterns-clean-code', NULL, 'Perfectionnez votre code grâce aux design patterns éprouvés et aux principes du Clean Code.', 'Cette masterclass couvre le Gang of Four, SOLID, et les anti-patterns courants. Chaque concept sera illustré par des exemples en C# et TypeScript, suivis d’exercices de refactoring collaboratif.', '2025-05-06 21:21:00', NULL),
(21, NULL, 'Webinaire Introduction à Rust pour la Programmation Système', 'webinaire-introduction-rust-programmation-systeme', NULL, 'Entrez dans l’univers de Rust et ses garanties de mémoire sans garbage collector.', 'Ce webinaire expliquera les notions de propriété (ownership), de borrowing et lifetimes, et vous guidera dans l’écriture d’un petit serveur HTTP minimaliste avec Actix.', '2025-05-06 21:22:00', NULL),
(22, NULL, 'Bootcamp Data Visualization avec D3.js', 'bootcamp-data-visualization-avec-d3js', NULL, 'Maîtrisez la création de visualisations interactives et dynamiques avec D3.js.', 'Sur 4 jours, vous apprendrez à manipuler le DOM pour générer graphiques personnalisés, gérer les transitions et intégrer des données en temps réel. Projet fil rouge : dashboard de suivi de performances.', '2025-05-06 21:23:00', NULL),
(23, NULL, 'Séminaire Cloud Native et Serverless', 'seminaire-cloud-native-serverless', NULL, 'Explorez les architectures serverless et les services managés dans AWS, GCP et Azure.', 'Ce séminaire couvre Lambda/Cloud Functions, API Gateway, Step Functions et la gestion des IAM. Sessions pratiques de déploiement et monitoring.', '2025-05-06 21:24:00', NULL),
(24, NULL, 'Atelier Front-end Moderne : Vue.js et Nuxt 3', 'atelier-frontend-moderne-vuejs-nuxt3', NULL, 'Développez des SPAs performantes et SEO-friendly avec Vue.js et Nuxt 3.', 'Vous configurerez un projet Nuxt, explorerez le Server-Side Rendering, et optimiserez les performances via la génération statique. Exercice final : blog multi-langues avec gestion d’authentification JWT.', '2025-05-06 21:25:00', NULL),
(25, NULL, 'Conférence QA & Testing Automation', 'conference-qa-testing-automation', NULL, 'Découvrez comment automatiser efficacement les tests fonctionnels et non fonctionnels.', 'Interventions sur Selenium, Cypress, Playwright et Postman pour tester APIs. Focus sur l’intégration dans les pipelines CI/CD et la génération de rapports avancés.', '2025-05-06 21:26:00', NULL),
(26, NULL, 'Workshop Développement AR/VR avec Unity 2025', 'workshop-developpement-ar-vr-unity-2025', NULL, 'Initiez-vous à la création d’expériences immersives en réalité augmentée et virtuelle.', 'Programmation C#, intégration de modèles 3D, déploiement sur Meta Quest et ARKit/ARCore. Exercice : mini-jeu VR multijoueur.', '2025-05-06 21:27:00', NULL),
(27, NULL, 'Bootcamp SQL Avancé et Optimisation de Requêtes', 'bootcamp-sql-avance-optimisation-requetes', NULL, 'Perfectionnez vos compétences SQL pour interroger et optimiser des bases volumineuses.', 'Thèmes abordés : indexation, partitions, requêtes analytiques, et tuning de performance sur MySQL et PostgreSQL. Cas pratique : optimisation d’un entrepôt de données.', '2025-05-06 21:28:00', NULL),
(28, NULL, 'Masterclass React Native pour Applications Mobile', 'masterclass-react-native-applications-mobile', NULL, 'Créez des applications mobiles cross-platform performantes avec React Native.', 'Ateliers pratiques : composants natifs, gestion d’état avec Redux, animations et publication sur App Store / Google Play.', '2025-05-06 21:29:00', NULL),
(29, NULL, 'Webinaire GraphQL : Mise en Œuvre et Sécurisation', 'webinaire-graphql-mise-en-oeuvre-securisation', NULL, 'Tout savoir sur GraphQL, de la définition de schémas à la protection contre les abus.', 'Présentation des librairies Apollo et Relay, implémentation de directives de rate limiting, et contrôle d’accès par champs.', '2025-05-06 21:30:00', NULL),
(30, NULL, 'Séminaire Python pour l’Automatisation DevOps', 'seminaire-python-automatisation-devops', NULL, 'Utilisez Python pour automatiser vos flux DevOps et orchestrer l’infrastructure.', 'Scripts de déploiement, tests d’intégration, et utilisation de Fabric et Click pour des CLI sur mesure.', '2025-05-06 21:31:00', NULL),
(31, NULL, 'Workshop Cybersécurité Offensive et Pentesting', 'workshop-cybersecurite-offensive-pentesting', NULL, 'Apprenez les techniques de pentesting pour identifier et exploiter les vulnérabilités.', 'Lab virtualisé avec Kali Linux, exploitation de failles XSS, CSRF et SQLi, et rédaction de rapports professionnels.', '2025-05-06 21:32:00', NULL),
(32, NULL, 'Bootcamp Vue.js Avancé et Composition API', 'bootcamp-vuejs-avance-composition-api', NULL, 'Explorez la Composition API de Vue 3 et les patterns avancés de développement.', 'Création de plugins, optimisation de la réactivité et intégration de TypeScript.', '2025-05-06 21:33:00', NULL),
(33, NULL, 'Conférence Edge AI et Vision par Ordinateur', 'conference-edge-ai-vision-par-ordinateur', NULL, 'Découvrez comment déployer des modèles de computer vision sur les appareils edge.', 'Cas d’usage : reconnaissance d’objets, détection de gestes et classification en temps réel avec TensorFlow Lite et OpenVINO.', '2025-05-06 21:34:00', NULL),
(34, NULL, 'Masterclass Java 17 et Patterns Modernes', 'masterclass-java-17-patterns-modernes', NULL, 'Mettez à jour vos connaissances Java avec les nouveautés de la version 17.', 'Scénarios pratiques sur les records, sealed classes, et performance de la JVM.', '2025-05-06 21:35:00', NULL),
(35, NULL, 'Atelier Go Lang : Écosystème et Concurrence', 'atelier-go-lang-ecosysteme-concurrence', NULL, 'Maîtrisez les goroutines, les channels, et les modules Go pour des applications performantes.', 'Exercices sur le pattern worker pool, services gRPC, et packaging modulable.', '2025-05-06 21:36:00', NULL),
(36, NULL, 'Bootcamp NoSQL : MongoDB et Cassandra', 'bootcamp-nosql-mongodb-cassandra', NULL, 'Comprenez les modèles de données NoSQL et déployez des clusters distribués.', 'Comparaison entre MongoDB et Cassandra, sharding, réplication et tuning.', '2025-05-06 21:37:00', NULL),
(37, NULL, 'Webinaire Accessibilité Web et RGAA', 'webinaire-accessibilite-web-rgaa', NULL, 'Garantissez l’accès de vos sites aux personnes en situation de handicap.', 'Mise en œuvre des bonnes pratiques WCAG et du référentiel RGAA, avec audits automatiques et guides de conformité.', '2025-05-06 21:38:00', NULL),
(38, NULL, 'Séminaire Blockchain Privée et Hyperledger', 'seminaire-blockchain-privee-hyperledger', NULL, 'Créez et gérez des réseaux blockchain privés avec Hyperledger Fabric.', 'Architecture réseau, Chaincode en Go, et gestion des identités avec Fabric CA.', '2025-05-06 21:39:00', NULL),
(39, NULL, 'Workshop Deep Learning et PyTorch', 'workshop-deep-learning-pytorch', NULL, 'Initiez-vous aux réseaux de neurones profonds avec PyTorch.', 'Construction de modèles CNN, RNN et entraînement distribué sur GPU. Étude de cas classification d’images.', '2025-05-06 21:40:00', NULL),
(40, NULL, 'Masterclass API RESTful avec ASP.NET Core', 'masterclass-api-restful-aspnet-core', NULL, 'Construisez des APIs performantes et sécurisées avec ASP.NET Core 6.', 'Versioning, authentification JWT, et documentation Swagger intégrée.', '2025-05-06 21:41:00', NULL),
(41, NULL, 'Atelier Data Science Éthique et Confidentialité', 'atelier-data-science-ethique-confidentialite', NULL, 'Explorez les enjeux de la vie privée et de l’éthique en data science.', 'Techniques de differential privacy, anonymisation k-anonymity, et méthodologies d’évaluation des biais.', '2025-05-06 21:42:00', NULL),
(42, NULL, 'Bootcamp PHP 8 et Framework Laravel', 'bootcamp-php-8-framework-laravel', NULL, 'Développez des applications web robustes avec Laravel 9 et PHP 8.', 'ORM Eloquent, middleware, queues, et tests unitaires. Projet fil rouge : plateforme de e-commerce.', '2025-05-06 21:43:00', NULL),
(43, NULL, 'Conférence Cloud Security Posture Management', 'conference-cloud-security-posture-management', NULL, 'Renforcez la sécurité de vos environnements multi-cloud.', 'Outils CSPM, détection de drift, et intégration SIEM pour Azure, AWS et GCP.', '2025-05-06 21:44:00', NULL),
(44, NULL, 'Webinaire Introduction à Docker Swarm', 'webinaire-introduction-docker-swarm', NULL, 'Apprenez à orchestrer vos conteneurs avec Docker Swarm.', 'Configuration de services, scaling, et mise en place de réseaux overlay.', '2025-05-06 21:45:00', NULL),
(45, NULL, 'Workshop Programmation Fonctionnelle en Scala', 'workshop-programmation-fonctionnelle-scala', NULL, 'Adoptez la programmation fonctionnelle avec Scala et Cats.', 'Monades, functors et tests property-based avec ScalaTest.', '2025-05-06 21:46:00', NULL),
(46, NULL, 'Masterclass Monitoring & Observabilité avec ELK Stack', 'masterclass-monitoring-observabilite-elk-stack', NULL, 'Déployez et configurez Elasticsearch, Logstash et Kibana pour la supervision.', 'Collecte de logs, création de dashboards temps réel et alerting avec Watcher.', '2025-05-06 21:47:00', NULL),
(47, NULL, 'Bootcamp JavaScript Modernes : ES2025 et au-delà', 'bootcamp-javascript-modernes-es2025-au-dela', NULL, 'Découvrez les nouveautés ECMAScript 2025 et améliorez votre workflow JavaScript.', 'Pattern matching, import assertions, et optimisation de bundle avec Rollup.', '2025-05-06 21:48:00', NULL),
(48, NULL, 'Atelier Chatbots et NLP avec Rasa', 'atelier-chatbots-nlp-rasa', NULL, 'Créez des chatbots intelligents en utilisant Rasa Open Source.', 'Conception de stories, entraînement de pipelines NLU, et déploiement sur Docker.', '2025-05-06 21:49:00', NULL),
(101, NULL, 'Atelier Python pour l’IA Éthique', 'atelier-python-ia-ethique', NULL, 'Explorez les bonnes pratiques pour développer des modèles d’IA responsables.', 'Au cours de cet atelier de 2 jours, vous apprendrez à identifier et atténuer les biais, à appliquer des méthodes de privacy-preserving et à documenter chaque étape du cycle de vie de vos modèles. Des études de cas réels illustreront les enjeux éthiques.', '2025-05-06 21:50:00', NULL),
(102, NULL, 'Bootcamp Full-Stack JavaScript avec MERN', 'bootcamp-full-stack-javascript-mern', NULL, 'Maîtrisez le stack MongoDB, Express, React et Node pour créer des applications web complètes.', 'Pendant 6 semaines, vous développerez un projet fil rouge : une plateforme de partage de connaissances incluant authentification, dashboard en temps réel et API REST sécurisée. Chaque module comprend quiz et code review.', '2025-05-06 21:51:00', NULL),
(103, NULL, 'Webinaire DevOps et Sécurité Cloud', 'webinaire-devops-securite-cloud', NULL, 'Découvrez comment intégrer la sécurité dès la phase DevOps dans vos environnements cloud.', 'Ce webinaire d’1h30 présentera les outils de scanning de vulnérabilités, la gestion des secrets avec Vault et l’automatisation des audits de configuration sur AWS, GCP et Azure.', '2025-05-06 21:52:00', NULL),
(104, NULL, 'Masterclass Data Engineering avec Apache Airflow', 'masterclass-data-engineering-apache-airflow', NULL, 'Apprenez à orchestrer vos pipelines de données avec Airflow et Kubernetes.', 'Ce cours pratique de 3 jours couvrira la conception de DAGs, la gestion des dépendances et le monitoring avec Grafana. Un projet final consistera à ingérer, transformer et charger des données dans un data warehouse.', '2025-05-06 21:53:00', NULL),
(105, NULL, 'Atelier Introduction à Terraform et IaC', 'atelier-introduction-terraform-iac', NULL, 'Initiez-vous à l’infrastructure as code avec Terraform pour AWS et Azure.', 'Vous découvrirez les bases de la syntaxe HCL, la gestion de l’état et les modules réutilisables. Des exercices pratiques incluront la création d’un VPC, de sous-réseaux et de clusters Kubernetes.', '2025-05-06 21:54:00', NULL),
(106, NULL, 'Bootcamp React Avancé et Performance', 'bootcamp-react-avance-performance', NULL, 'Optimisez vos applications React pour une expérience utilisateur fluide.', 'Pendant 4 jours, vous aborderez le code-splitting, le lazy loading, les hooks personnalisés et le profiling avec React DevTools. Le module final porte sur l’optimisation SEO des SPA.', '2025-05-06 21:55:00', NULL),
(107, NULL, 'Séminaire Introduction à la Cryptographie Post-Quantique', 'seminaire-introduction-cryptographie-post-quantique', NULL, 'Comprenez les algorithmes résistants aux ordinateurs quantiques.', 'Ce séminaire de 1 jour présente les familles d’algorithmes lattices, code-based et multivariate, ainsi que leur implémentation en Rust. Un atelier de mise en œuvre vous guidera pour générer clés et signatures.', '2025-05-06 21:56:00', NULL),
(108, NULL, 'Workshop Développement Mobile iOS avec SwiftUI', 'workshop-dev-mobile-ios-swiftui', NULL, 'Créez des interfaces modernes pour iPhone et iPad avec SwiftUI.', 'En 3 jours, vous apprendrez à structurer vos vues, gérer l’état avec Combine et intégrer Swift Package Manager. Projet pratique : une application de suivi de tâches synchronisée avec iCloud.', '2025-05-06 21:57:00', NULL),
(109, NULL, 'Conférence Big Data et Gouvernance des Données', 'conference-big-data-gouvernance-donnees', NULL, 'Explorez les enjeux de la qualité et du contrôle des données à grande échelle.', 'Intervenants experts en data management aborderont le Data Catalog, la data lineage et les cadres réglementaires (GDPR, CCPA). Sessions de workshop pour définir une politique de gouvernance adaptée.', '2025-05-06 21:58:00', NULL),
(110, NULL, 'Atelier Front-end avec Svelte et Sapper', 'atelier-frontend-svelte-sapper', NULL, 'Découvrez Svelte, le framework qui compile votre code en JavaScript optimisé.', 'Sur 2 jours, vous créerez des composants réactifs, gérerez la navigation avec Sapper et optimiserez le bundle. Cas pratique : un blog statique généré à la volée.', '2025-05-06 21:59:00', NULL),
(111, NULL, 'Masterclass Kubernetes Security', 'masterclass-kubernetes-security', NULL, 'Sécurisez vos clusters Kubernetes contre les menaces internes et externes.', 'Vous apprendrez à configurer RBAC, Network Policies et Pod Security Policies. Ateliers pratiques : audit avec kube-bench, scan d’images conteneurisées et mise en place de Falco pour la détection d’intrusion.', '2025-05-06 22:00:00', NULL),
(112, NULL, 'Bootcamp Data Science avec R et Shiny', 'bootcamp-data-science-r-shiny', NULL, 'Analysez et visualisez vos données interactives avec R et Shiny.', 'En 5 jours, vous découvrirez tidyverse, ggplot2 et développerez des dashboards déployables sur RStudio Connect. Un projet final consistera à construire une application d’analyse de sentiments.', '2025-05-06 22:01:00', NULL),
(113, NULL, 'Webinaire Performance SQL et Indexation', 'webinaire-performance-sql-indexation', NULL, 'Optimisez vos requêtes SQL et comprenez le fonctionnement des index.', 'Ce webinaire d’1h présente les plans d’exécution, l’utilisation des index composites et les stratégies de partitionnement pour MySQL et PostgreSQL.', '2025-05-06 22:02:00', NULL),
(114, NULL, 'Workshop Blockchain Privée avec Corda', 'workshop-blockchain-privee-corda', NULL, 'Mettez en place un réseau Corda pour des transactions inter-entreprises.', 'Apprenez la structure des états, la rédaction des CorDapps en Kotlin et le déploiement d’un réseau multi-nœuds. Cas pratique : contrat de vente automobile.', '2025-05-06 22:03:00', NULL),
(115, NULL, 'Séminaire Architecture Micro-Frontends', 'seminaire-architecture-micro-frontends', NULL, 'Découvrez comment découper vos frontends en micro-applications indépendantes.', 'Ce séminaire d’1 jour couvre Module Federation, les conteneurs web et le versioning, avec mise en place d’un portail unifié en React et Vue intégrés.', '2025-05-06 22:04:00', NULL),
(116, NULL, 'Atelier Graph Databases avec Neo4j', 'atelier-graph-databases-neo4j', NULL, 'Explorez les bases de données graphe pour modéliser des relations complexes.', 'Au programme : Cypher Query Language, import de données, indexation et algorithmes de graph analytics. Projet : mise en place d’un réseau social prédictif.', '2025-05-06 22:05:00', NULL),
(117, NULL, 'Bootcamp Programmation Réactive avec RxJava', 'bootcamp-programmation-reactive-rxjava', NULL, 'Adoptez le paradigme réactif pour vos applications Java robustes.', 'Vous étudierez les opérateurs de flux, la gestion de backpressure et l’intégration avec Spring WebFlux. Exercices : pipeline de traitement d’événements en temps réel.', '2025-05-06 22:06:00', NULL),
(118, NULL, 'Masterclass CI/CD avec GitHub Actions', 'masterclass-cicd-github-actions', NULL, 'Automatisez vos workflows de build, test et déploiement avec GitHub Actions.', 'Ce cours de 2 jours couvre la création de workflows, la gestion des secrets et l’utilisation de matrices pour tester plusieurs environnements simultanément.', '2025-05-06 22:07:00', NULL),
(119, NULL, 'Webinaire Développement d’APIs GraphQL with Hasura', 'webinaire-apis-graphql-hasura', NULL, 'Générez instantanément une API GraphQL sécurisée à partir de votre base Postgres.', 'Présentation de Hasura, configuration des permissions basées rôles et mise en place de déclencheurs en temps réel.', '2025-05-06 22:08:00', NULL),
(120, NULL, 'Workshop IoT Sécurité et Protocoles', 'workshop-iot-securite-protocoles', NULL, 'Comprenez les enjeux de sécurité des objets connectés et les protocoles IoT.', 'Vous étudierez MQTT, CoAP, DTLS et mettrez en place une passerelle sécurisée avec Mosquitto et OpenSSL.', '2025-05-06 22:09:00', NULL),
(121, NULL, 'Séminaire Introduction à Erlang et Elixir', 'seminaire-introduction-erlang-elixir', NULL, 'Découvrez la puissance des langages Erlang et Elixir pour les systèmes distribués.', 'Ce séminaire d’une journée couvre OTP, supervision trees et la création d’API avec Phoenix framework.', '2025-05-06 22:10:00', NULL),
(122, NULL, 'Bootcamp Mobile Cross-Platform avec Xamarin', 'bootcamp-mobile-cross-platform-xamarin', NULL, 'Développez des applications mobiles multiplateformes en C# avec Xamarin.Forms.', 'En 4 jours, vous apprendrez le layout, la liaison de données et les services REST. Projet : application de gestion de tâches synchronisée avec Azure Mobile Apps.', '2025-05-06 22:11:00', NULL),
(123, NULL, 'Atelier Performance JavaScript et Web Assembly', 'atelier-performance-javascript-web-assembly', NULL, 'Accélérez vos applications web en combinant JS et WASM.', 'Présentations sur Emscripten, Rust-to-WASM et optimisation des performances côté client. Exercice : portage d’une bibliothèque de calcul intensif en WASM.', '2025-05-06 22:12:00', NULL),
(124, NULL, 'Masterclass OAuth 2.1 et OpenID Connect', 'masterclass-oauth2-1-openid-connect', NULL, 'Implémentez des flux d’authentification sécurisés pour vos applications.', 'Ce cours de 2 jours couvre les grant types, les JWT, PKCE et la configuration de serveurs d’autorisation avec Keycloak.', '2025-05-06 22:13:00', NULL),
(125, NULL, 'Webinaire Tests de Charge avec JMeter', 'webinaire-tests-charge-jmeter', NULL, 'Simulez et analysez la performance de vos applications sous forte charge.', 'Ce webinaire présente les scénarios de test, la collecte de métriques et l’interprétation des rapports avec Grafana.', '2025-05-06 22:14:00', NULL),
(126, NULL, 'Workshop Programmation C en Systèmes Embarqués', 'workshop-programmation-c-systemes-embarques', NULL, 'Développez du firmware en C pour microcontrôleurs ARM.', 'Vous utiliserez Keil MDK, configurerez les interruptions et optimiserez le code pour minimiser la consommation énergétique.', '2025-05-06 22:15:00', NULL),
(127, NULL, 'Séminaire Vue 3 Composition API et TypeScript', 'seminaire-vue3-composition-api-typescript', NULL, 'Combinez Vue 3 et TypeScript pour un développement plus sûr et maintenable.', 'Ce séminaire d’1 jour présente les bénéfices de la Composition API, l’injection de dépendances et la génération automatique de types.', '2025-05-06 22:16:00', NULL),
(128, NULL, 'Bootcamp React VR et WebXR', 'bootcamp-react-vr-webxr', NULL, 'Créez des expériences immersives sur le web avec React 360 et WebXR.', 'En 3 jours, vous apprendrez à gérer la caméra 360, l’interaction utilisateur et le déploiement sur navigateurs compatibles.', '2025-05-06 22:17:00', NULL),
(129, NULL, 'Atelier Automatisation BI avec Power BI & DAX', 'atelier-automatisation-bi-power-bi-dax', NULL, 'Analysez vos données et créez des rapports dynamiques avec Power BI.', 'Vous découvrirez les fonctions avancées de DAX, l’optimisation de modèles et la publication de dashboards.', '2025-05-06 22:18:00', NULL),
(130, NULL, 'Masterclass Cloud Native Java avec Micronaut', 'masterclass-cloud-native-java-micronaut', NULL, 'Développez des microservices légers et performants avec Micronaut.', 'Ce cours couvre la compilation ahead-of-time, l’injection de dépendance et l’intégration avec Kubernetes.', '2025-05-06 22:19:00', NULL),
(131, NULL, 'Webinaire Introduction aux ChatOps', 'webinaire-introduction-chatops', NULL, 'Découvrez comment intégrer vos outils DevOps dans des plateformes de chat.', 'Présentation de Hubot, Lita et Microsoft Teams Bots, avec démonstration de déploiement et automatisation simple de tâches.', '2025-05-06 22:20:00', NULL),
(132, NULL, 'Workshop Data Lakehouse avec Delta Lake', 'workshop-data-lakehouse-delta-lake', NULL, 'Combinez les avantages des data lakes et des entrepôts de données avec Delta Lake.', 'Vous apprendrez à gérer les versions de données, optimiser les performances et configurer les transactions ACID sur Databricks.', '2025-05-06 22:21:00', NULL),
(133, NULL, 'Séminaire Introduction à Kotlin Multiplatform', 'seminaire-introduction-kotlin-multiplatform', NULL, 'Partagez du code entre Android, iOS et le web avec Kotlin Multiplatform.', 'Ce séminaire d’1 jour présente la configuration Gradle, la création de librairies partagées et l’interopérabilité native.', '2025-05-06 22:22:00', NULL),
(134, NULL, 'Bootcamp C# 10 et .NET 6 Modernes', 'bootcamp-csharp-10-net6-modernes', NULL, 'Exploitez les nouveautés de C# 10 et .NET 6 pour vos applications d’entreprise.', 'Vous découvrirez les global usings, records, minimal APIs et la performance améliorée du runtime.', '2025-05-06 22:23:00', NULL),
(135, NULL, 'Atelier Programming Quantum with Qiskit', 'atelier-programming-quantum-qiskit', NULL, 'Initiez-vous à la programmation quantique avec Qiskit et IBM Quantum Experience.', 'Vous apprendrez les qubits, les portes quantiques et réaliserez votre premier algorithme de Grover.', '2025-05-06 22:24:00', NULL),
(136, NULL, 'Masterclass Observability avec OpenTelemetry', 'masterclass-observability-opentelemetry', NULL, 'Implémentez le tracing distribué et la métrique unifiée avec OpenTelemetry.', 'Ce cours de 2 jours couvre l’instrumentation, la collecte de données via Jaeger et Prometheus, et l’analyse dans Grafana.', '2025-05-06 22:25:00', NULL),
(137, NULL, 'Webinaire Introduction à Flutter Web', 'webinaire-introduction-flutter-web', NULL, 'Créez des applications web interactives avec Flutter.', 'Présentation du workflow, des widgets responsives et du déploiement sur Firebase Hosting.', '2025-05-06 22:26:00', NULL),
(138, NULL, 'Workshop Programmation Sécurisée en C++', 'workshop-programmation-securisee-cpp', NULL, 'Apprenez les techniques pour écrire du code C++ résistant aux vulnérabilités.', 'Vous verrez l’usage de smart pointers, l’analyse statique avec clang-tidy et la mitigation des buffer overflows.', '2025-05-06 22:27:00', NULL),
(139, NULL, 'Séminaire Introduction à GitOps', 'seminaire-introduction-gitops', NULL, 'Adoptez Git comme source de vérité pour vos déploiements Kubernetes.', 'Ce séminaire couvre Flux et Argo CD, la gestion des secrets et le rollback automatique.', '2025-05-06 22:28:00', NULL),
(140, NULL, 'Bootcamp RPA avec UiPath', 'bootcamp-rpa-uipath', NULL, 'Automatisez vos tâches répétitives en entreprise avec UiPath.', 'De la conception du processus à l’implémentation d’un robot, en passant par Orchestrator et l’analyse des logs.', '2025-05-06 22:29:00', NULL),
(141, NULL, 'Atelier Motion Design pour le Web', 'atelier-motion-design-web', NULL, 'Apprenez à animer vos interfaces web avec CSS, SVG et JS.', 'Exercices sur keyframes, bibliothèque Lottie et intégration dans React/Vue.', '2025-05-06 22:30:00', NULL),
(142, NULL, 'Masterclass Python pour la Finance Quantitative', 'masterclass-python-finance-quantitative', NULL, 'Développez des modèles financiers et des backtests avec Python.', 'Couverture de pandas, NumPy, statsmodels et implémentation de stratégies algorithmique.', '2025-05-06 22:31:00', NULL),
(143, NULL, 'Webinaire Introduction à Apache Pulsar', 'webinaire-introduction-apache-pulsar', NULL, 'Découvrez le messaging distribué et le streaming d’événements avec Pulsar.', 'Présentation des topics, partitions, et comparaison avec Kafka. Cas d’usage : ingestion de logs en temps réel.', '2025-05-06 22:32:00', NULL),
(144, NULL, 'Workshop Programmation Fonctionnelle en Haskell', 'workshop-programmation-fonctionnelle-haskell', NULL, 'Adoptez les concepts de pureté et immutabilité avec Haskell.', 'Apprentissage du monad, typeclasses et création d’un petit compilateur DSL.', '2025-05-06 22:33:00', NULL),
(145, NULL, 'Séminaire Performance .NET et Profiling', 'seminaire-performance-dotnet-profiling', NULL, 'Diagnostiquez et optimisez vos applications .NET avec Visual Studio Profiler.', 'Techniques de memory dumps, CPU sampling et instrumentation manuelle.', '2025-05-06 22:34:00', NULL),
(146, 'uploads/articles/article_683db06d595f3.webp', 'Bootcamp WebAssembly et Rust', 'bootcamp-webassembly-et-rust', NULL, 'Combinez Rust et WASM pour des modules ultra-performants sur le web.', 'De la configuration toolchain à l’intégration JS, avec mesures de performance.', '2025-05-06 22:35:00', '2025-06-02 15:08:45'),
(149, 'uploads/articles/article_683db062f2330.jpg', 'Webinaire Introduction à GraphQL Federation', 'webinaire-introduction-à-graphql-federation', NULL, 'Apprenez à fédérer plusieurs services GraphQL en une seule API unifiée.', 'Présentation d’Apollo Federation, SDL composition et résolution des schémas.', '2025-05-06 22:38:00', '2025-06-02 15:08:34'),
(150, 'uploads/articles/article_683db04a48170.jpeg', 'Lel Workshop Automatisation Infrastructure avec Pulumi', 'lel-workshop-automatisation-infrastructure-avec-pulumi', NULL, 'Programmez votre infrastructure cloud avec des langages usuels grâce à Pulumi.', 'Comparaison IaC déclarative vs impérative, et mise en place de stacks AWS/Azure en TypeScript.', '2025-05-06 22:39:00', '2025-06-02 15:08:10'),
(201, NULL, 'Introduction à l\'Intelligence Artificielle', 'introduction-intelligence-artificielle', NULL, 'Découvrez les bases de l’intelligence artificielle et ses applications.', 'L’intelligence artificielle (IA) est un domaine en pleine expansion qui englobe une variété de techniques permettant aux machines d\'imiter des comportements humains. Dans cet article, nous allons explorer les concepts fondamentaux de l’IA, y compris l\'apprentissage automatique, l\'apprentissage profond, et les systèmes experts. Nous aborderons également les défis éthiques liés à l\'utilisation de l’IA dans des secteurs tels que la santé, l\'éducation et la sécurité. Au fil de cet article, vous découvrirez comment l’IA transforme le monde moderne et les compétences nécessaires pour exceller dans ce domaine en constante évolution.', '2025-05-06 21:10:00', NULL),
(202, NULL, 'Développement Web avec React', 'developpement-web-react', NULL, 'Apprenez à créer des applications web dynamiques avec React.', 'React est une bibliothèque JavaScript populaire pour la construction d’interfaces utilisateur. Dans cet article, nous vous guiderons à travers les étapes de création d’une application web intégrant React. Vous apprendrez à définir un projet, à structurer votre code, et à utiliser des composants réutilisables pour améliorer la maintenabilité. De plus, nous examinerons comment gérer l’état de votre application avec Redux et comment effectuer des appels API pour récupérer des données dynamiques. À la fin de cet article, vous serez en mesure de développer des applications web modernes et réactives.', '2025-05-06 21:11:00', NULL),
(203, NULL, 'Les Fondamentaux de Python', 'fondamentaux-python', NULL, 'Initiez-vous à la programmation avec Python, le langage polyvalent.', 'Python est un langage de programmation très apprécié pour sa simplicité et sa lisibilité. Cet article vous présentera les bases de Python, y compris les types de données, les structures de contrôle, et les fonctions. Nous aborderons également les bibliothèques populaires comme NumPy et Pandas pour le traitement des données. À travers des exemples pratiques, vous apprendrez à écrire des scripts Python pour automatiser des tâches quotidiennes et effectuer des analyses de données. Ce guide est parfait pour les débutants souhaitant entrer dans le monde de la programmation.', '2025-05-06 21:12:00', NULL),
(204, NULL, 'Introduction à Docker', 'introduction-docker', NULL, 'Découvrez comment Docker facilite le déploiement d\'applications.', 'Docker est une plateforme qui permet de développer, expédier et exécuter des applications dans des conteneurs. Dans cet article, nous explorerons les concepts de base de Docker, y compris la création et la gestion de conteneurs. Vous apprendrez également à configurer vos environnements de développement et de production avec Docker Compose. Grâce à des exemples concrets, nous montrerons comment Docker peut simplifier les workflows de déploiement et garantir la cohérence entre les différentes étapes du cycle de vie de vos applications.', '2025-05-06 21:13:00', NULL),
(205, NULL, 'Fondamentaux du Machine Learning', 'fondamentaux-machine-learning', NULL, 'Initiez-vous aux concepts de base du machine learning.', 'Le machine learning, ou apprentissage automatique, est une branche de l’IA qui permet aux ordinateurs d’apprendre à partir de données. Cet article vous introduira aux principaux concepts du machine learning, tels que les algorithmes supervisés et non supervisés, ainsi que l’importance de la préparation des données. Nous examinerons des cas d’utilisation pratiques, notamment la classification d’images et la prévision de séries temporelles. À la fin de cet article, vous aurez une compréhension claire de la façon dont le machine learning fonctionne et comment il peut être appliqué dans divers domaines.', '2025-05-06 21:14:00', NULL),
(206, NULL, 'Création d\'API REST avec Node.js', 'creation-api-rest-nodejs', NULL, 'Apprenez à créer une API RESTful avec Node.js et Express.', 'Node.js a révolutionné le développement web en permettant l’exécution de JavaScript côté serveur. Cet article vous guidera à travers le processus de création d’une API RESTful en utilisant Node.js et le framework Express. Vous apprendrez à définir des routes, à gérer les requêtes et les réponses, et à interagir avec une base de données. En suivant notre exemple, vous serez capable de créer une API qui peut servir des données à vos applications front-end ou à des clients tiers. À la fin de l’article, vous aurez une solide compréhension des API REST et de leur mise en œuvre avec Node.js.', '2025-05-06 21:15:00', NULL),
(207, NULL, 'Introduction au Cloud Computing', 'introduction-cloud-computing', NULL, 'Découvrez les principes fondamentaux du cloud computing.', 'Le cloud computing a transformé la façon dont nous stockons et accédons aux données. Dans cet article, nous explorerons les différents modèles de déploiement du cloud, y compris le cloud public, privé et hybride. Nous discuterons également des principaux fournisseurs de services cloud tels qu’AWS, Azure et Google Cloud. À travers des études de cas, nous montrerons comment les entreprises utilisent le cloud pour améliorer leur agilité et réduire leurs coûts d’exploitation. Cet article est idéal pour ceux qui souhaitent comprendre les bases du cloud computing et son impact sur les entreprises modernes.', '2025-05-06 21:16:00', NULL),
(208, NULL, 'Les Bases de la Sécurité Informatique', 'bases-securite-informatique', NULL, 'Initiez-vous aux fondamentaux de la sécurité informatique.', 'La sécurité informatique est un enjeu majeur pour toutes les organisations. Dans cet article, nous aborderons les concepts clés de la sécurité, y compris les menaces courantes, la gestion des risques et les meilleures pratiques pour protéger vos systèmes. Nous expliquerons également l’importance de la sensibilisation à la sécurité et comment former vos employés pour prévenir les cyberattaques. En suivant cet article, vous obtiendrez une vue d’ensemble des défis de sécurité auxquels les entreprises sont confrontées et des stratégies pour y faire face.', '2025-05-06 21:17:00', NULL),
(209, NULL, 'Introduction à la Blockchain', 'introduction-blockchain', NULL, 'Découvrez comment fonctionne la technologie blockchain.', 'La blockchain est une technologie décentralisée qui permet d’enregistrer des transactions de manière sécurisée et transparente. Cet article vous expliquera les principes fondamentaux de la blockchain, y compris les concepts de blocs, de chaînes et de consensus. Nous aborderons également les applications de la blockchain au-delà des cryptomonnaies, telles que la gestion des chaînes d’approvisionnement et les contrats intelligents. Grâce à des exemples concrets, vous comprendrez comment la blockchain peut transformer divers secteurs et quelles compétences sont nécessaires pour travailler dans ce domaine.', '2025-05-06 21:18:00', NULL),
(210, NULL, 'Développement d\'Applications Mobiles avec Flutter', 'developpement-applications-mobiles-flutter', NULL, 'Créez des applications mobiles multiplateformes avec Flutter.', 'Flutter est un framework open-source développé par Google qui permet de créer des applications mobiles pour Android et iOS à partir d’une seule base de code. Dans cet article, nous vous montrerons comment démarrer avec Flutter, en installant l’environnement de développement et en créant votre première application. Vous apprendrez à utiliser les widgets Flutter pour construire une interface utilisateur attrayante et réactive. À travers des exemples, nous démontrerons comment Flutter facilite le développement d’applications mobiles modernes et performantes.', '2025-05-06 21:19:00', NULL),
(211, NULL, 'L\'Économie Numérique et ses Enjeux', 'economie-numerique-enjeux', NULL, 'Analysez les impacts de l\'économie numérique sur le monde moderne.', 'L’économie numérique a radicalement changé la façon dont nous interagissons, travaillons et consommons. Cet article explore les enjeux clés de l’économie numérique, y compris l’impact sur l’emploi, la vie privée, et la régulation des données. Nous discuterons des opportunités et des défis que présente la transformation numérique pour les entreprises et les gouvernements. À travers des études de cas, vous découvrirez comment certaines organisations réussissent à tirer parti des technologies numériques pour innover et croître.', '2025-05-06 21:20:00', NULL),
(212, NULL, 'Développement Web avec Angular', 'developpement-web-angular', NULL, 'Créez des applications web dynamiques avec Angular.', 'Angular est un framework puissant pour construire des applications web modernes et dynamiques. Dans cet article, nous vous guiderons à travers les étapes de création d’une application Angular, en mettant l’accent sur la structure du projet, la gestion des composants et des services. Nous aborderons également la gestion de l’état avec NgRx et comment effectuer des appels HTTP pour récupérer des données. À la fin de cet article, vous aurez les compétences nécessaires pour développer des applications web robustes en utilisant Angular.', '2025-05-06 21:21:00', NULL),
(213, NULL, 'Introduction à la Programmation Fonctionnelle', 'introduction-programmation-fonctionnelle', NULL, 'Découvrez les principes de la programmation fonctionnelle.', 'La programmation fonctionnelle est un paradigme qui repose sur l\'utilisation de fonctions pures et l\'immuabilité des données. Cet article vous introduira aux concepts clés de la programmation fonctionnelle, y compris les fonctions d’ordre supérieur, les closures et les monades. Nous examinerons des langages comme Haskell et Scala qui adoptent ce paradigme, ainsi que des techniques pour appliquer la programmation fonctionnelle dans des langages impératifs comme JavaScript. À la fin de cet article, vous aurez une compréhension claire de la programmation fonctionnelle et de ses avantages.', '2025-05-06 21:22:00', NULL),
(214, NULL, 'Création de Jeux Vidéo avec Unity', 'creation-jeux-video-unity', NULL, 'Initiez-vous au développement de jeux vidéo avec Unity.', 'Unity est l’un des moteurs de jeu les plus populaires au monde, permettant de créer des jeux 2D et 3D. Dans cet article, nous vous guiderons à travers le processus de développement d’un jeu vidéo simple en utilisant Unity. Vous apprendrez à gérer les assets, à créer des scènes, et à programmer des interactions avec C#. À travers des exercices pratiques, vous découvrirez comment concevoir un jeu captivant et comment publier votre jeu sur différentes plateformes. Ce guide est parfait pour ceux qui souhaitent entrer dans le monde du développement de jeux vidéo.', '2025-05-06 21:23:00', NULL),
(215, NULL, 'Introduction à la Réalité Virtuelle', 'introduction-realite-virtuelle', NULL, 'Explorez les concepts de la réalité virtuelle et ses applications.', 'La réalité virtuelle (RV) est une technologie immersive qui simule des environnements réels ou imaginaires. Dans cet article, nous discuterons des technologies sous-jacentes à la réalité virtuelle, y compris les casques VR et les systèmes de suivi. Nous examinerons également les applications de la RV dans divers domaines, tels que le jeu vidéo, l’éducation et la formation professionnelle. Grâce à des exemples concrets, vous comprendrez comment la RV transforme l’expérience utilisateur et les compétences requises pour développer des applications de réalité virtuelle.', '2025-05-06 21:24:00', NULL),
(216, NULL, 'Les Enjeux de la Data Science', 'enjeux-data-science', NULL, 'Analysez l’impact de la data science dans le monde moderne.', 'La data science est un domaine interdisciplinaire qui utilise des techniques statistiques et informatiques pour extraire des connaissances à partir des données. Cet article explore les enjeux clés de la data science, notamment la collecte, l’analyse et l’interprétation des données. Nous discuterons également des défis éthiques liés à l’utilisation des données, tels que la vie privée et la transparence. À travers des études de cas, vous découvrirez comment la data science peut être utilisée pour résoudre des problèmes complexes dans divers secteurs, tels que la santé, le marketing et la finance.', '2025-05-06 21:25:00', NULL),
(217, NULL, 'Sécurisation des Applications Web', 'securisation-applications-web', NULL, 'Initiez-vous aux meilleures pratiques de sécurisation des applications web.', 'La sécurisation des applications web est essentielle pour protéger les données des utilisateurs et garantir l’intégrité des systèmes. Cet article vous présentera les meilleures pratiques pour sécuriser vos applications web, y compris la validation des entrées, l’authentification et l’autorisation, ainsi que la gestion des sessions. Nous examinerons également les outils et les techniques pour détecter et prévenir les vulnérabilités courantes, telles que XSS et CSRF. À travers des exemples pratiques, vous apprendrez à renforcer la sécurité de vos applications web.', '2025-05-06 21:26:00', NULL),
(218, NULL, 'Introduction à l\'Internet des Objets (IoT)', 'introduction-internet-des-objets', NULL, 'Découvrez les principes de base de l\'Internet des Objets.', 'L’Internet des Objets (IoT) désigne l’ensemble des objets connectés à Internet, capables de collecter et d’échanger des données. Cet article vous introduira aux concepts fondamentaux de l’IoT, y compris les capteurs, les protocoles de communication et les plateformes cloud. Nous aborderons également les défis liés à la sécurité et à la gestion des données dans le contexte de l’IoT. Avec des exemples concrets, vous comprendrez comment l’IoT transforme notre quotidien et les compétences nécessaires pour travailler dans ce domaine en pleine expansion.', '2025-05-06 21:27:00', NULL);
INSERT INTO `articles` (`id`, `image`, `title`, `slug`, `category_id`, `introduction`, `content`, `created_at`, `updated_at`) VALUES
(219, NULL, 'Développement de Microservices avec Spring Boot', 'developpement-microservices-spring-boot', NULL, 'Créez des applications basées sur une architecture microservices avec Spring Boot.', 'Spring Boot est un framework Java qui facilite le développement de microservices. Dans cet article, nous explorerons les principes de base des microservices et comment Spring Boot peut être utilisé pour les développer. Vous apprendrez à configurer des services, à gérer la communication entre microservices, et à déployer vos applications dans un environnement cloud. À travers des exemples pratiques, vous découvrirez comment concevoir des applications évolutives et résilientes.', '2025-05-06 21:28:00', NULL),
(220, NULL, 'Introduction à la Programmation Orientée Objet', 'introduction-programmation-orientee-objet', NULL, 'Découvrez les concepts de base de la programmation orientée objet.', 'La programmation orientée objet (POO) est un paradigme qui repose sur l’utilisation d’objets pour modéliser des systèmes complexes. Cet article vous présentera les concepts clés de la POO, y compris les classes, les objets, l’héritage et le polymorphisme. Nous examinerons des langages de programmation populaires qui utilisent la POO, tels que Java et C#. À travers des exemples concrets, vous apprendrez à appliquer ces concepts dans vos propres projets de développement.', '2025-05-06 21:29:00', NULL),
(221, NULL, 'Création de Sites Web avec WordPress', 'creation-sites-web-wordpress', NULL, 'Initiez-vous à la création de sites web avec WordPress.', 'WordPress est l’un des systèmes de gestion de contenu (CMS) les plus populaires au monde. Dans cet article, nous vous guiderons à travers le processus de création d’un site web avec WordPress, de l’installation à la personnalisation des thèmes et des plugins. Vous apprendrez à créer et gérer des articles, des pages, et à optimiser votre site pour le référencement. À travers des exemples pratiques, vous découvrirez comment WordPress peut transformer votre présence en ligne.', '2025-05-06 21:30:00', NULL),
(222, NULL, 'Les Bases de l\'Analyse de Données', 'bases-analyse-donnees', NULL, 'Découvrez les fondements de l\'analyse de données.', 'L’analyse de données est un processus qui transforme des données brutes en informations exploitables. Cet article vous présentera les étapes clés de l’analyse de données, y compris la collecte, le nettoyage et l’exploration des données. Nous aborderons également les outils couramment utilisés, tels que Excel, R et Python, pour effectuer des analyses. À travers des études de cas, vous apprendrez comment tirer parti de l’analyse de données pour prendre des décisions éclairées.', '2025-05-06 21:31:00', NULL),
(223, NULL, 'Introduction à la Programmation Web', 'introduction-programmation-web', NULL, 'Initiez-vous aux concepts de base de la programmation web.', 'La programmation web est un domaine en constante évolution qui nécessite une compréhension des langages de programmation, des frameworks et des technologies web. Cet article vous introduira aux fondements de la programmation web, y compris HTML, CSS et JavaScript. Vous apprendrez à créer des pages web interactives et à les styliser avec CSS. À travers des exemples pratiques, vous découvrirez comment construire des applications web modernes.', '2025-05-06 21:32:00', NULL),
(224, NULL, 'Développement d\'Applications avec Swift', 'developpement-applications-swift', NULL, 'Créez des applications iOS en utilisant Swift.', 'Swift est un langage de programmation moderne développé par Apple pour créer des applications iOS et macOS. Dans cet article, nous vous guiderons à travers le processus de développement d’une application iOS simple en utilisant Swift. Vous apprendrez à manipuler les interfaces utilisateur, à gérer les données et à publier vos applications sur l’App Store. À travers des exemples pratiques, vous découvrirez comment Swift facilite le développement d’applications performantes et élégantes.', '2025-05-06 21:33:00', NULL),
(225, NULL, 'Web Scraping avec Python', 'web-scraping-python', NULL, 'Initiez-vous à l\'extraction de données sur le web avec Python.', 'Le web scraping est une technique qui permet d’extraire des données de pages web. Dans cet article, nous explorerons les outils et bibliothèques en Python, comme Beautiful Soup et Scrapy, pour effectuer du scraping de manière efficace. Vous apprendrez à manipuler des éléments HTML, à gérer les sessions et à stocker les données extraites dans un format structuré. À travers des exemples pratiques, vous découvrirez comment automatiser le processus d’extraction de données sur le web.', '2025-05-06 21:34:00', NULL),
(226, NULL, 'Développement de Chatbots avec Python', 'developpement-chatbots-python', NULL, 'Créez des chatbots intelligents en utilisant Python.', 'Les chatbots sont des programmes qui simulent des conversations humaines. Cet article vous introduira aux concepts de base du développement de chatbots en utilisant Python. Vous apprendrez à utiliser des bibliothèques comme NLTK et Rasa pour créer des chatbots capables de comprendre et traiter le langage naturel. À travers des exemples pratiques, vous découvrirez comment déployer votre chatbot sur différentes plateformes de messagerie.', '2025-05-06 21:35:00', NULL),
(227, NULL, 'Introduction à la Programmation avec C#', 'introduction-programmation-csharp', NULL, 'Découvrez les bases de la programmation avec C#.', 'C# est un langage de programmation polyvalent développé par Microsoft, utilisé pour le développement d’applications Windows, web et mobiles. Cet article vous présentera les concepts fondamentaux de C#, y compris les types de données, les structures de contrôle et la programmation orientée objet. Vous apprendrez à créer des applications simples et à utiliser Visual Studio pour le développement. À la fin de cet article, vous disposerez des connaissances nécessaires pour débuter en C#.', '2025-05-06 21:36:00', NULL),
(228, NULL, 'Création de Sites E-commerce avec WooCommerce', 'creation-sites-ecommerce-woocommerce', NULL, 'Initiez-vous à la création de boutiques en ligne avec WooCommerce.', 'WooCommerce est une extension de WordPress qui permet de créer des boutiques en ligne facilement. Dans cet article, nous vous guiderons à travers le processus d’installation de WooCommerce, de la configuration des produits à la gestion des paiements. Vous apprendrez également à personnaliser votre boutique avec des thèmes et des plugins. À travers des exemples pratiques, vous serez en mesure de lancer votre propre boutique en ligne.', '2025-05-06 21:37:00', NULL),
(229, NULL, 'Les Fondamentaux de la Cyber Sécurité', 'fondamentaux-cyber-securite', NULL, 'Découvrez les bases de la cybersécurité et comment protéger vos systèmes.', 'La cybersécurité est essentielle pour protéger les informations sensibles des entreprises. Cet article aborde les concepts de base de la cybersécurité, y compris les menaces courantes, les mesures préventives et les meilleures pratiques pour sécuriser vos systèmes. Vous apprendrez également comment mettre en place une stratégie de sécurité efficace et comment sensibiliser vos employés aux risques. À la fin de cet article, vous serez mieux préparé à protéger vos données contre les cyberattaques.', '2025-05-06 21:38:00', NULL),
(230, NULL, 'Introduction à l\'APIs REST', 'introduction-api-rest', NULL, 'Découvrez comment créer et utiliser des APIs REST.', 'Les APIs REST sont devenues un standard dans le développement d’applications web. Cet article vous introduira aux concepts de base des APIs REST, y compris les méthodes HTTP, le format JSON et les bonnes pratiques de conception. Vous apprendrez à créer une API REST avec Node.js et Express, et comment l’utiliser dans vos applications front-end. À travers des exemples pratiques, vous découvrirez comment les APIs REST peuvent améliorer l’interopérabilité de vos systèmes.', '2025-05-06 21:39:00', NULL),
(231, NULL, 'Développement de Jeux avec Unreal Engine', 'developpement-jeux-unreal-engine', NULL, 'Initiez-vous au développement de jeux vidéo avec Unreal Engine.', 'Unreal Engine est un moteur de jeu puissant utilisé pour créer des jeux 3D de haute qualité. Cet article vous guidera à travers les fonctionnalités d’Unreal Engine, y compris le blueprint visual scripting et la création de niveaux. Vous apprendrez à concevoir des mécaniques de jeu et à intégrer des graphismes de qualité professionnelle. À travers des exemples pratiques, vous découvrirez comment développer un jeu complet avec Unreal Engine.', '2025-05-06 21:40:00', NULL),
(232, NULL, 'Introduction aux Systèmes de Gestion de Bases de Données', 'introduction-sgbd', NULL, 'Découvrez les principes fondamentaux des SGBD.', 'Les systèmes de gestion de bases de données (SGBD) sont essentiels pour le stockage et la gestion des données. Cet article vous présentera les concepts de base des SGBD, y compris les bases de données relationnelles et non relationnelles. Vous apprendrez à concevoir des schémas de données, à écrire des requêtes SQL et à interagir avec des bases de données via des ORM. À la fin de cet article, vous aurez une compréhension solide des SGBD et de leur importance dans les applications modernes.', '2025-05-06 21:41:00', NULL),
(233, NULL, 'Les Bases de la Programmation Web Full Stack', 'bases-programmation-web-full-stack', NULL, 'Initiez-vous aux concepts de la programmation web full stack.', 'La programmation web full stack implique la maîtrise à la fois du développement front-end et back-end. Cet article vous introduira aux technologies clés utilisées dans le développement full stack, y compris HTML, CSS, JavaScript, Node.js et MongoDB. Vous apprendrez à créer des applications web complètes, de la conception de l’interface utilisateur à la gestion des données sur le serveur. À travers des exemples pratiques, vous découvrirez comment devenir un développeur full stack compétent.', '2025-05-06 21:42:00', NULL),
(234, NULL, 'Développement d\'Applications avec Ruby on Rails', 'developpement-applications-ruby-on-rails', NULL, 'Initiez-vous au développement d’applications web avec Ruby on Rails.', 'Ruby on Rails est un framework de développement web qui facilite la création d’applications complexes. Cet article vous présentera les concepts fondamentaux de Ruby on Rails, y compris les conventions de nommage, les migrations de base de données et le routage. Vous apprendrez à créer une application web simple, à gérer les utilisateurs et à déployer votre application. À la fin de cet article, vous aurez les compétences nécessaires pour commencer à développer avec Ruby on Rails.', '2025-05-06 21:43:00', NULL),
(235, NULL, 'Introduction à l\'Analyse des Données avec R', 'introduction-analyse-donnees-r', NULL, 'Découvrez comment utiliser R pour l’analyse des données.', 'R est un langage de programmation et un environnement logiciel pour l’analyse statistique et graphique. Cet article vous introduira aux fonctionnalités de R, y compris la manipulation de données avec dplyr, la visualisation avec ggplot2, et l’analyse statistique. À travers des exemples pratiques, vous apprendrez à effectuer des analyses de données et à créer des visualisations impactantes. Cet article est idéal pour ceux qui souhaitent se lancer dans l’analyse de données avec R.', '2025-05-06 21:44:00', NULL),
(236, NULL, 'Création de Sites Web Responsifs', 'creation-sites-web-responsifs', NULL, 'Initiez-vous aux techniques de création de sites web responsifs.', 'La création de sites web responsifs est essentielle pour garantir une expérience utilisateur optimale sur tous les appareils. Cet article vous présentera les principes du design responsif, y compris l’utilisation de grilles flexibles, de media queries, et d’unités relatives. Vous apprendrez à concevoir des sites web qui s’adaptent à différentes tailles d’écran, tout en préservant la convivialité et l’esthétique. À travers des exemples pratiques, vous découvrirez comment créer des sites web modernes et accessibles.', '2025-05-06 21:45:00', NULL),
(237, NULL, 'Les Bases du SEO (Search Engine Optimization)', 'bases-seo', NULL, 'Découvrez les fondamentaux du référencement naturel.', 'Le SEO, ou référencement naturel, est une stratégie essentielle pour améliorer la visibilité de votre site sur les moteurs de recherche. Cet article vous introduira aux concepts de base du SEO, y compris l’optimisation des mots-clés, la création de contenu de qualité, et l’optimisation technique. Vous apprendrez à mettre en place des pratiques SEO efficaces pour attirer un trafic organique et améliorer le classement de votre site. À la fin de cet article, vous aurez les connaissances nécessaires pour débuter en SEO.', '2025-05-06 21:46:00', NULL),
(238, NULL, 'Développement de Services Web avec PHP', 'developpement-services-web-php', NULL, 'Créez des services web robustes avec PHP.', 'PHP est un langage de script largement utilisé pour le développement web. Cet article vous présentera les concepts fondamentaux du développement de services web avec PHP, y compris la création d’APIs RESTful et la gestion des bases de données. Vous apprendrez à développer des applications web dynamiques et à interagir avec des applications front-end. À travers des exemples pratiques, vous découvrirez comment PHP peut être utilisé pour créer des services web performants et sécurisés.', '2025-05-06 21:47:00', NULL),
(239, NULL, 'Introduction à l\'Utilisation de Git et GitHub', 'introduction-git-github', NULL, 'Découvrez les bases du contrôle de version avec Git et GitHub.', 'Git est un système de contrôle de version distribué qui permet de suivre les modifications apportées à un projet. Cet article vous introduira aux concepts de base de Git, y compris les commits, les branches et les merges. Vous apprendrez également à utiliser GitHub pour héberger vos projets et collaborer avec d’autres développeurs. À travers des exemples pratiques, vous découvrirez comment gérer efficacement vos projets de développement et faciliter le travail en équipe.', '2025-05-06 21:48:00', NULL),
(240, NULL, 'Développement d\'Applications avec ASP.NET', 'developpement-applications-aspnet', NULL, 'Initiez-vous au développement d’applications web avec ASP.NET.', 'ASP.NET est un framework de développement web développé par Microsoft qui permet de créer des applications robustes et évolutives. Cet article vous présentera les concepts fondamentaux d’ASP.NET, y compris la création de contrôleurs, la gestion des routages et l’interaction avec des bases de données. Vous apprendrez à développer des applications web dynamiques et à implémenter des fonctionnalités avancées. À la fin de cet article, vous aurez les compétences nécessaires pour commencer à développer avec ASP.NET.', '2025-05-06 21:49:00', NULL),
(241, NULL, 'Les Fondamentaux de l\'Apprentissage Automatique', 'fondamentaux-apprentissage-automatique', NULL, 'Initiez-vous aux concepts de base de l\'apprentissage automatique.', 'L’apprentissage automatique est une discipline de l’intelligence artificielle qui enseigne aux machines comment apprendre à partir de données. Cet article vous introduira aux différents types d’apprentissage, y compris l’apprentissage supervisé, non supervisé et par renforcement. Vous apprendrez à utiliser des bibliothèques comme Scikit-learn et TensorFlow pour développer des modèles d’apprentissage automatique. À travers des exemples pratiques, vous découvrirez comment appliquer ces techniques à des problèmes réels.', '2025-05-06 21:50:00', NULL),
(242, NULL, 'Introduction aux Frameworks JavaScript', 'introduction-frameworks-javascript', NULL, 'Découvrez les différents frameworks JavaScript pour le développement web.', 'Les frameworks JavaScript facilitent le développement d’applications web dynamiques et interactives. Cet article vous présentera les principaux frameworks JavaScript, y compris React, Angular et Vue.js. Vous apprendrez à choisir le framework adapté à votre projet et à comprendre les avantages et inconvénients de chacun. À travers des exemples pratiques, vous découvrirez comment utiliser ces frameworks pour créer des applications web modernes.', '2025-05-06 21:51:00', NULL),
(243, NULL, 'Création d\'Applications avec Django', 'creation-applications-django', NULL, 'Initiez-vous au développement d’applications web avec Django.', 'Django est un framework web Python qui facilite le développement d’applications sécurisées et évolutives. Cet article vous présentera les concepts fondamentaux de Django, y compris les modèles, les vues et les templates. Vous apprendrez à créer une application web complète, de la gestion des utilisateurs à l’intégration de bases de données. À la fin de cet article, vous aurez les compétences nécessaires pour commencer à développer avec Django.', '2025-05-06 21:52:00', NULL),
(244, NULL, 'Les Bases de la Programmation Java', 'bases-programmation-java', NULL, 'Découvrez les fondements de la programmation avec Java.', 'Java est un langage de programmation orienté objet largement utilisé pour le développement d’applications d’entreprise. Cet article vous introduira aux concepts fondamentaux de Java, y compris les types de données, les structures de contrôle et la gestion des exceptions. Vous apprendrez à créer des programmes simples et à utiliser des bibliothèques Java populaires. À la fin de cet article, vous disposerez des connaissances nécessaires pour débuter en Java.', '2025-05-06 21:53:00', NULL),
(245, NULL, 'Introduction aux Technologies Front-End', 'introduction-technologies-front-end', NULL, 'Découvrez les technologies clés du développement front-end.', 'Le développement front-end est essentiel pour créer des interfaces utilisateur attrayantes et fonctionnelles. Cet article vous présentera les technologies clés du front-end, y compris HTML, CSS et JavaScript. Vous apprendrez à créer des pages web réactives et à utiliser des frameworks comme Bootstrap pour améliorer l’expérience utilisateur. À travers des exemples pratiques, vous découvrirez comment concevoir des interfaces web modernes.', '2025-05-06 21:54:00', NULL),
(246, NULL, 'Développement d\'Applications avec Kotlin', 'developpement-applications-kotlin', NULL, 'Initiez-vous au développement d’applications Android avec Kotlin.', 'Kotlin est un langage moderne qui facilite le développement d’applications Android. Cet article vous présentera les concepts fondamentaux de Kotlin, y compris les types de données, la gestion des nulls et la programmation orientée objet. Vous apprendrez à créer des applications Android simples et à utiliser les bibliothèques Android. À travers des exemples pratiques, vous découvrirez comment développer des applications performantes avec Kotlin.', '2025-05-06 21:55:00', NULL),
(247, NULL, 'Les Fondamentaux de la Programmation Réactive', 'fondamentaux-programmation-reactive', NULL, 'Initiez-vous aux concepts de base de la programmation réactive.', 'La programmation réactive est un paradigme qui permet de gérer les flux de données de manière asynchrone. Cet article vous introduira aux concepts clés de la programmation réactive, y compris les observables, les flux et la gestion des événements. Vous apprendrez à utiliser des bibliothèques comme RxJS pour implémenter des solutions réactives dans vos applications. À travers des exemples pratiques, vous découvrirez comment la programmation réactive peut améliorer la réactivité de vos systèmes.', '2025-05-06 21:56:00', NULL),
(248, NULL, 'Création de Podcasts avec Audacity', 'creation-podcasts-audacity', NULL, 'Initiez-vous à la création de podcasts en utilisant Audacity.', 'Audacity est un logiciel libre qui permet de créer et d’éditer des fichiers audio. Cet article vous guidera à travers le processus de création d’un podcast, en vous montrant comment enregistrer, éditer et mixer vos fichiers audio. Vous apprendrez également à publier votre podcast sur des plateformes de diffusion. À travers des exemples pratiques, vous découvrirez les astuces pour produire un podcast de qualité professionnelle.', '2025-05-06 21:57:00', NULL),
(249, NULL, 'Introduction à la Programmation avec Go', 'introduction-programmation-go', NULL, 'Découvrez les bases de la programmation avec Go.', 'Go, également connu sous le nom de Golang, est un langage de programmation moderne développé par Google. Cet article vous introduira aux concepts fondamentaux de Go, y compris les types de données, les fonctions et la gestion des goroutines. Vous apprendrez à créer des applications simples et à utiliser les bibliothèques standard de Go. À la fin de cet article, vous disposerez des connaissances nécessaires pour débuter en Go.', '2025-05-06 21:58:00', NULL),
(250, NULL, 'Les Bases de l\'Automatisation avec Ansible', 'bases-automatisation-ansible', NULL, 'Initiez-vous à l’automatisation des tâches avec Ansible.', 'Ansible est un outil open-source utilisé pour l’automatisation des tâches IT. Cet article vous introduira aux concepts fondamentaux d’Ansible, y compris la gestion des playbooks et des inventaires. Vous apprendrez à automatiser le déploiement d’applications, la configuration des serveurs et la gestion des mises à jour. À travers des exemples pratiques, vous découvrirez comment Ansible peut simplifier vos opérations IT.', '2025-05-06 21:59:00', NULL),
(251, NULL, 'Développement de Services Cloud avec AWS', 'developpement-services-cloud-aws', NULL, 'Initiez-vous au développement de services cloud avec AWS.', 'AWS (Amazon Web Services) est une plateforme leader dans le domaine des services cloud. Cet article vous présentera les services fondamentaux d’AWS, y compris EC2, S3, et Lambda. Vous apprendrez à déployer des applications sur AWS, à gérer les ressources cloud et à utiliser les services de base de données. À travers des exemples pratiques, vous découvrirez comment tirer parti d’AWS pour développer des applications évolutives et performantes.', '2025-05-06 22:00:00', NULL),
(252, 'uploads/articles/article_683db03f533b4.jpeg', 'fghdh', 'fghdh', NULL, 'sfsd', 'bssdbs', '2025-05-07 05:55:34', '2025-06-02 15:07:59'),
(269, 'uploads/articles/article_683db03362e20.webp', 'Ipsam qui quidem cil', 'ipsam-qui-quidem-cil', NULL, 'Ipsa amet reiciend', 'Aperiam reprehenderi', '2025-05-21 04:37:45', '2025-06-02 15:07:47'),
(270, 'uploads/articles/article_683db0167bf15.png', 'Esse labore lorem 4444444444444444444', 'esse-labore-lorem-4444444444444444444', NULL, 'Ducimus inventore d', 'Pariatur Sit pariat', '2025-05-21 04:38:02', '2025-06-02 15:07:18'),
(285, 'uploads/articles/article_683da1ab8ecc7.png', 'Et nemo aut ut repre++++++++++', 'et-nemo-aut-ut-repre++++++++++', NULL, 'Aut ut exercitatione', 'Eiusmod qui mollitia', '2025-05-30 19:37:14', '2025-06-02 14:05:47'),
(291, 'uploads/articles/article_683da0b229b40.png', 'Eos ut nesciunt ma', 'eos-ut-nesciunt-ma', NULL, 'Fugiat soluta nesci', 'Ut maiores facere et', '2025-05-31 00:55:57', '2025-06-02 14:01:38'),
(298, 'uploads/articles/article_683daff4c6c18.jpg', 'Nulla sit iste sint', 'nulla-sit-iste-sint', NULL, 'Fuga Laudantium ex', 'Est molestiae eum p', '2025-06-02 13:57:54', '2025-06-04 11:03:08'),
(299, 'uploads/articles/article_6873729a142f0.jpg', 'Eum quae commodi duc', 'eum-quae-commodi-duc', NULL, 'Sequi amet id repu', 'Minima magnam nisi c', '2025-07-13 09:47:22', NULL);

-- --------------------------------------------------------

--
-- Structure de la table `categories`
--

CREATE TABLE `categories` (
  `id` int NOT NULL,
  `name` varchar(50) NOT NULL,
  `slug` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Structure de la table `comments`
--

CREATE TABLE `comments` (
  `id` int NOT NULL,
  `content` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `article_id` int NOT NULL,
  `user_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `comments`
--

INSERT INTO `comments` (`id`, `content`, `created_at`, `article_id`, `user_id`) VALUES
(1, 'ttt', '2025-05-07 15:06:22', 150, 4),
(2, 'fff', '2025-05-07 16:00:48', 149, 4),
(3, 'dfvdfv', '2025-05-07 16:01:13', 149, 4),
(4, '', '2025-05-07 16:02:31', 149, 4),
(10, '&lt;w&lt;wx&lt;&lt;w', '2025-05-07 16:35:51', 13, 4),
(13, '', '2025-05-12 04:42:58', 149, 4),
(14, '', '2025-05-12 04:43:00', 149, 4),
(15, '', '2025-05-12 04:43:02', 149, 4),
(16, '$$$$', '2025-05-12 04:43:07', 149, 4),
(28, 'dvdsd', '2025-05-17 20:45:01', 150, 4),
(29, 'cqscq', '2025-05-17 20:45:06', 150, 4),
(31, 'cc&lt;&lt;c', '2025-05-21 02:23:07', 252, 4),
(32, 'c&lt;&lt;&lt;', '2025-05-21 02:23:11', 252, 4),
(33, '', '2025-05-21 03:15:08', 127, 4),
(39, 'qzsdqs', '2025-05-21 04:28:46', 270, 4),
(70, 'fbfdbfd', '2025-05-27 08:04:04', 270, 4),
(72, 'sqsq', '2025-05-27 20:36:09', 270, 4),
(77, 'vc ', '2025-05-28 04:08:48', 270, 4),
(78, '---------------------xwcvvvvvvvvvvvv', '2025-05-28 04:09:01', 270, 4),
(79, 'aaaaaaaaaaaaaaaa', '2025-05-28 04:12:12', 149, 4),
(80, 'xvxcxc', '2025-05-30 18:37:25', 285, 4),
(82, '', '2025-05-30 19:33:08', 285, 4),
(86, '}\r\n\r\nprivate function handleImageUpload(?array $file): ?string\r\n{\r\n    if (!$file || $file[&#039;error&#039;] !== UPLOAD_ERR_OK) {\r\n        return null;\r\n    }\r\n\r\n    $uploadDir = &#039;uploads/articles/&#039;;\r\n    if (!is_dir($uploadDir)) {\r\n        mkdir($uploadDir, 0755, true);\r\n    }\r\n\r\n    // Vérification du type MIME réel\r\n    $finfo = finfo_open(FILEINFO_MIME_TYPE);\r\n    $mime = finfo_file($finfo, $file[&#039;tmp_name&#039;]);\r\n    $allowedMimes = [&#039;image/jpeg&#039;, &#039;image/png&#039;, &#039;image/gif&#039;, &#039;image/webp&#039;];\r\n\r\n    if (!in_array($mime, $allowedMimes)) {\r\n        throw new \\Exception(&quot;Format d&#039;image non supporté&quot;);\r\n    }\r\n\r\n    $extension = pathinfo($file[&#039;name&#039;], PATHINFO_EXTENSION);\r\n    $filename = uniqid(&#039;article_&#039;) . &#039;.&#039; . $extension;\r\n    $destination = $uploadDir . $filename;\r\n\r\n    if (!move_uploaded_file($file[&#039;tmp_name&#039;], $destination)) {\r\n        throw new \\Exception(&quot;Erreur lors du téléchargement de l&#039;image&quot;);\r\n    }\r\n\r\n    return $destination;\r\n}\r\nAméliorations apportées\r\nSéparation des responsabilités :\r\n\r\nExtraction de la logique de traitement d&#039;image dans une méthode dédiée\r\nUtilisation d&#039;une classe Utils pour les fonctions communes\r\nSécurité renforcée :\r\n\r\nVérification du type MIME réel des fichiers\r\nGestion centralisée des erreurs avec try/catch\r\nValidation plus stricte des permissions\r\nQualité de code :\r\n\r\nChemins de vues normalisés\r\nTypage des retours et paramètres (à ajouter selon version PHP)\r\nMessages d&#039;erreur plus précis\r\nMaintenabilité :\r\n\r\nCode plus facile à tester unitairement\r\nMeilleure organisation des dépendances\r\nPour compléter cette refactorisation, vous devriez :\r\n\r\nCréer une classe Utils avec les méthodes communes\r\nMettre à jour votre fichier admin.php pour qu&#039;il utilise la nouvelle version\r\nVérifier que toutes les dépendances sont correctement chargées\r\nCette version devrait résoudre vos problèmes tout en offrant une base plus solide pour les évolutions ', '2025-05-31 00:16:23', 291, 15),
(87, 'Code plus facile à tester unitairement\r\nMeilleure organisation des dépendances\r\nPour compléter cette refactorisation, vous devriez :\r\n\r\nCréer une classe Utils avec les méthodes communes\r\nMettre à jour votre fichier admin.php pour qu&amp;#039;il utilise la nouvelle version\r\nVérifier que toutes les dépendances sont correctement chargées\r\nCette version devrait résoudre vos problèmes tout en offrant une base plus solide pour les évolutions', '2025-05-31 00:16:32', 291, 15),
(88, 'Code plus facile à tester unitairement\r\nMeilleure organisation des dépendances\r\nPour compléter cette refactorisation, vous devriez :\r\n\r\nCréer une classe Utils avec les méthodes communes\r\nMettre à jour votre fichier admin.php pour qu&amp;#039;il utilise la nouvelle version\r\nVérifier que toutes les dépendances sont correctement chargées\r\nCette version devrait résoudre vos problèmes tout en offrant une base plus solide pour les évolutions', '2025-05-31 00:16:49', 291, 4),
(89, 'qq', '2025-05-31 07:17:51', 252, 4),
(93, 'scsq', '2025-06-02 07:14:45', 291, 4),
(94, 'xw', '2025-06-02 12:55:04', 285, 4),
(95, 'sxqxQ', '2025-06-02 12:59:30', 298, 4),
(97, 'vxw vwx', '2025-06-02 14:18:38', 298, 4),
(99, 'vsdf', '2025-06-04 08:26:01', 298, 4),
(100, 'zqd', '2025-07-13 08:47:55', 299, 4);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `username` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','default') NOT NULL DEFAULT 'default',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`, `role`, `created_at`, `update_at`) VALUES
(1, 'lele', 'lele@gmail.com', '$2y$10$YT8GAbqV64LqMcW9w8Nt6eJ5Zf5jUjNu5Ng2tEShKV3X1dARNjQiK', 'admin', '2025-04-23 14:24:14', '2025-04-23 16:05:36'),
(2, 'qytotavyw', 'typucito@mailinator.com', '$2y$10$fqilEaIjXp7BTeI6doD3o.9nn8oDZ1HPr2OIutiGfYE4mmwfVt/He', 'default', '2025-04-23 15:10:16', '2025-04-23 15:10:16'),
(3, 'hufyhaj', 'honecuvyfi@mailinator.com', '$2y$10$y53PRCFIo1kkzPeYIfjz5uFEbgg/gIf8iqs0UwoRNLm/SoskX2JNi', 'default', '2025-05-06 19:07:16', '2025-05-06 19:07:16'),
(4, 'admin', 'admin@gmail.com', '$2y$10$t.g8RvTttm23/0fETBjDsupXc.eROzmQ7ry1FNlkIs/TEdsHqbNXe', 'admin', '2025-05-06 19:10:08', '2025-05-06 19:11:23'),
(5, 'user', 'user@gmail.com', '$2y$10$3fLuf9TX.TRuBetQMocQRed0VmK.Yes9hl5XkneIog.zmt5iReohW', 'default', '2025-05-07 06:53:21', '2025-05-07 06:53:21'),
(6, 'gyjynupyw', 'razyha@mailinator.com', '$2y$10$Hy1mA3UbttsOmvtvuVVtwegF1vaUeWFj/RjNutmpy.N00V9dwI1KG', 'default', '2025-05-26 17:22:41', '2025-05-26 17:22:41'),
(7, 'nibixiho', 'aaaaa@gmail.com', '$2y$10$9zyI/UlOUjGg4veqd83pNu12ja4DTOBlNW2HqsECPIyMQWJjG3ndG', 'default', '2025-05-26 18:05:54', '2025-05-26 18:05:54'),
(8, 'mabukeqaxi', 'hehokys@mailinator.com', '$2y$10$hvp5DUJSFA1s1aDhOzkQxOuass2ai9oevZmBORSi8/yHzEtEDmZty', 'default', '2025-05-27 08:05:21', '2025-05-27 08:05:21'),
(9, 'qyfaxuv', 'falyguq@mailinator.com', '$2y$10$xlo0oRdcn.VK0JsU/U4D3eTT1UVPfWlO8qzROUX3XBLD0.F4BZDCu', 'default', '2025-05-30 19:06:14', '2025-05-30 19:06:14'),
(10, 'puxyjic', 'foqepap@mailinator.com', '$2y$10$EC8KOT2Q4j9wjBl/GGP.Ku9/I8hKeN/lw22CpU4PVMUtSzZ0qGBtC', 'default', '2025-05-30 19:06:56', '2025-05-30 19:06:56'),
(11, 'hevera', 'lulo@mailinator.com', '$2y$10$sqP5ssYr/K47vY05pimOS..dn73R4yqcItwn1F/bcc9YKBWPp4ZZq', 'default', '2025-05-30 19:07:53', '2025-05-30 19:07:53'),
(12, 'zoxugylig', 'cyqofuzoxe@mailinator.com', '$2y$10$UIMHeCP93Yk0RxeZPhEW8uAWW.7FgTism1KbhokHM7JyjNsjQlxrq', 'default', '2025-05-30 19:22:21', '2025-05-30 19:22:21'),
(13, 'vecyhasam', 'nupul@mailinator.com', '$2y$10$VYahXYtz0hugZUqRg0wL1ecjQhl6VJOvhTnSzIGA8EkDPD/tm.2Ru', 'default', '2025-05-30 19:32:35', '2025-05-30 19:32:35'),
(14, 'wenykaxe', 'xagohawedu@mailinator.com', '$2y$10$VMVoZRQLuYdOCrNg2OatGeW4zQ4gLFd0IUlZ37SYWg96nkFMSDE1q', 'default', '2025-05-30 21:37:42', '2025-05-30 21:37:42'),
(15, 'jakeda', 'nyxugeb@mailinator.com', '$2y$10$SMQ/nJBlV8wfFj5Fdb7bLORVJpBtMUj6RindFJENGcZRIJYw8KHVq', 'default', '2025-05-31 00:10:58', '2025-05-31 00:10:58');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`),
  ADD KEY `ForeignKeyCategory` (`category_id`);

--
-- Index pour la table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`);

--
-- Index pour la table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `ForeignKeyArticle` (`article_id`),
  ADD KEY `ForeignKeyUser` (`user_id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=300;

--
-- AUTO_INCREMENT pour la table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Contraintes pour la table `comments`
--
ALTER TABLE `comments`
  ADD CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
